apiVersion: v1
kind: Namespace
metadata:
  name: authz-ns
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
  namespace: authz-ns
spec:
  selector:
    matchLabels:
      app: authz
  replicas: 1
  template:
    metadata:
      labels:
        app: authz
    spec:
      serviceAccountName: authz-sa
      containers:
      - name: authz-container
        image: salrashid123/ext-authz-server
        volumeMounts:
        - name: keyfile
          mountPath: "/data/certs"
          readOnly: true        
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: AUTHZ_ALLOWED_USERS
          valueFrom:
            configMapKeyRef:
              name: authz-config
              key: allowedusers                               
        - name: AUTHZ_SERVER_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: authz-config
              key: authzserverkeyid
        - name: AUTHZ_ISSUER
          valueFrom:
            configMapKeyRef:
              name: authz-config
              key: authzissuer              
      volumes:
      - name: keyfile
        secret:
          secretName: svc-secret
---
apiVersion: v1
data:
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeEFFN2VCNnF1Z1h5Q0FHM3loaDdwa0RrVDY1cEh5bVgrUDdLZkl1cGpmNTl2c2RvCjkxYlNQOUM4SDA3cFNBR1FPMU1WL3hGajlWc3dnc0NnNFI2b3RtZzVQVjJIZTk1bFpkSHRPY1U1RFhJZy9wYmgKTGRLWGJpNjZHbFZlSzZBQlpPVVczV1l0bk5IRCs5MWdWdW9lSlQvRHd0R0djcDRpZ25rZ1hma2lFbTRzdys0cwpmYjRxZHQ1b0xieVZwbVc2eDljZmE3dnMyV1RmVVJpQ3JCb1VxZ0JvLys0V1RpVUxtbUhTR1pIT2p6d2E4V3RyCnRPUUdzQUZqSWJubzg1anA2TW5HR0daUFlaYkRBYS9iM3k1dStZcFc3eXBacnZEOEJndEtWamd0UWdaaExBR2UKek10MHVhM0RSclduS3FUWjBCSi9FeXhPR3VISnJMc24wMGZuTVFJREFRQUJBb0lCQVFDZnYzbGVyMi9xYVlvWAo2SDZJNG1kMDJ4SzV0cWJLMVRXZHBOd1hvaVN4TENnRVk3WXpVTG5QZFNxK1FheDBHWUlhTjkrSG9mN2NMRlJmClhPeENUcUNtK2s4Y3Fxd1AwdlRGaGRGWThsdExrQ2RBR0d5eTBoN0ZtS1BwYm9adis5cm5CcWdhRG50Q2d0eSsKM0hEMnBaMm9NazQwN0Z3dDhxQ2h3bU1VOUVaR3ljSVJ4d1RGQjh4R3BzczhnRmMrZlRBbXZHRkkvczhhY2x1KworWG12UGt3MGx6K2RMYU5zbmUweUJIVk1QRnRuY3FoYnNGYm5iQjhPQU10V3NWYlR3VTYwT1ZlWi9vT1lKVlk5CnZ0dU1RNElBaTVrTXg4QVdRMVVEdlcyWm51R3BRa3I2ZFoyWVAvSU1PWEdheXdiZ2NIUFVpdHJXM2lJWVlXK1UKTklWV1hrQTVBb0dCQVBkOU1lc1FkdUNzbmdXTnZ0SWpyTlVFYWtiWGtnMHZidytkUkliSXF5MkJ4L3R5V2hpbQpxRk5ZY05qWkVMcXA1QzNmM2hsTy9rOUs4eHhKTElZbG9ZZzE5NDhEYnBPaFZrOFNkRkdncENZQzRxL2ZCUHcrCmtBRlFFS2haZWx3S2oyU3JmNThCQ3JoSWUxS1BIYlFmVEYvSlo3SkJuZEl3NzkvMXA5clU2d1dMQW9HQkFNcSsKeWQrN0w4d3BDWk50bWpEVVRXbUdxM0xtRkxCekJNaHdtVjJOT0tiVEZha01WeUV0U09SUUZPSmJ4Rnd1V3g1egpqM25McTlpdlFnTktMUExTVEYvRHRlajJsemdOZDlZRy85WFcrNkhlWjg0MVhOVUhFMFhzVTZNbTFFQXlhZGZ1CkFBbm94VGgvTnFZdkY4MXFDTTl0bDlCc2p4OGtsT3lYcnJHS2ovV3pBb0dBS0pDMnUrYkk5VzZWd0NkSm5id0gKT2lzdEdFdUJQdlFGYWpQRzVhakNsZ1R0dUlNM3pVNlR6SVYwaWJhYWpWNEhicFdCRy9qY3FqYUl2cHduMWgwWQo2dkNka1MxbzFIM2ZYYnFTb2thSVlVcWJ5V1B1dDBHeDdPVW90YzlreE8xZUw0d0VzUlZFb293TzJxdG1uUDE4ClVUNzc1alhuSG1xekJxeUhSTkVkYkowQ2dZQWRnUEFkcDc3SDVmem53RjVjMXJoQk1BREpJcVJHSFNiSUNHSzUKRTNENERlV3NDUWl3NGtjbU9tVWZuNTBPa1F4ZmZRK1crTVdVTGNUY2Q3SGMwQytmQy9ydjROcVdwSmNZeFVINwptMkpZNXVXU1EzK3ozR2k0bHpDQW9Jam9vcTEyWjhNSHJpRHRITTRXRnVwTzBTeGhDeUM1aXVLMDlIemJoU005CjROMGNNd0tCZ0dmWUpSbVg1cFc3cktvL08xWmw2b0c2VkJBNmZZWEllMjhYOXNaMFlDYlZJdVg4TWdSazJWcG0KeTQ3cW16RVEvMWt3V3RRelpPY2VQTThyZDhxVFRGUENrTTQ1UzFpZWg3cWpOU01WSWJsOEk2MzVVcUNDb2V0VwpWRHd2VWhWTE80bUJUMHAyRjhnNlduZ21weTlaQmgyQjUydzNSejlVeEhmZndkQzdoaFFECi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: svc-secret
  namespace: authz-ns
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-config
  namespace: authz-ns
data:
  allowedusers: "alice,bob,carol"
  authzserverkeyid: "DHFbpoIUqrY8t2zpA2qXfCmr5VO5ZEr4RzHU_-envvQ"
  authzissuer: "testing@secure.istio.io"
---
apiVersion: v1
kind: Service
metadata:
  name: authz
  namespace: authz-ns
  labels:
    app: authz
spec:
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: authz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authz-sa
  namespace: authz-ns
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authz-virtualservice
  namespace: authz-ns
spec:
  hosts:
  - authz
  gateways:
  - mesh
  http:      
  - route:
    - destination:
        host: authz   
    match:
    - sourceLabels:           
        istio: ingressgateway
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: authz-destination
  namespace: authz-ns
spec:
  host: "auth.authz-ns.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
##  ingress --> authz
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ing-authzserver-peer-authn-policy
  namespace: authz-ns
spec:
  selector:
    matchLabels:
      app: authz
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ing-authzserver-authz-policy
 namespace: authz-ns
spec:
 action: ALLOW
 selector:
   matchLabels:
     app: authz
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: "my-ext-authz-grpc"
  rules:
  - to:
    - operation:
        paths: ["/*"]     
---  
## default deny all
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: deny-all-authz-ns
 namespace: authz-ns
spec:
  {} 
---